# This is used to generate a new CSS file from the sass template files.

.PHONY: all
all:
	@sass --no-source-map custom_bulma.scss:../css/styles.css


.PHONY: watch
watch:
	@sass --watch --no-source-map custom_bulma.scss:../css/styles.css
